### ISSUE TITLE
Looking for Contact

### ISSUE THREAD

**Issue by leee** [jariz/trapped#6]
.

**Comment by jariz** [comment]
Hi. It's jari@trapped.io

**Comment by leee** [comment]
@jariz saw your mail just now, sent a reply. Let's just say you never set mail up properly.

**Comment by jariz** [comment]
Right, that suddenly broke I guess, it used to work.  
Will look into it, in the meantime, you can use my personal address, jarizw@gmail.com

**Comment by leee** [comment]
Forwarding now, thanks.
